name: Lint

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Upstream Nix using the Nix Installer from Determinate Systems
        uses: DeterminateSystems/nix-installer-action@main

      - name: Lint the Brewfile
        run: nix develop .#adhoc --command ./scripts/lint.sh
